# Generated by Django 3.0.4 on 2020-05-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao', models.IntegerField(null=True)),
                ('facebook', models.IntegerField(null=True)),
                ('nick_name', models.CharField(max_length=25, unique=True)),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=400, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
